### ISSUE TITLE
[동욱] 디테일 TODO LIST

### ISSUE THREAD

**Issue by doonguk** [woowa-techcamp-2020/bmart-6#88]
## 요약
- [x]  상품 디테일 페이지 단독 진입 시, 애니메이션 제거
- [x] 검색바 > 엔터로 검색
- [ ]  검색에서 리다이렉트
- [ ]  스크롤이벤트
- [ ] 배경에 하얀색 주기
- [x] 메인페이지 금액에 , 표기하기
- [ ] 더보기 어떻게 할지 생각하기

- [ ]  땡겨요
